<?php

namespace Databases\OsPosBundle\Repository;

/**
 * OsposTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsposTestRepository extends \Doctrine\ORM\EntityRepository
{
}
