<?php

namespace WebSiteBundle\Repository;

/**
 * CommitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitsRepository extends \Doctrine\ORM\EntityRepository
{
}
