
# Sonata User
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb


    class:
        user:   Application\Sonata\UserBundle\Entity\User
        group:  Application\Sonata\UserBundle\Entity\Group

# Sonata Blocks
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.stats:
            contexts:   [admin]
        sonata.admin.block.admin_list:
            contexts: [admin]    
        sonata.admin.block.search_result:
            contexts:   [admin]
            
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes            
        
# Sonata Admin        
sonata_admin:
    title:      Splash Db Connector
    title_logo: img/Splash-Logo_Ico.png
#    templates:
#        show:       AppBundle:Admin:Display_Client.html.twig        
    options:
#        title_mode:                     "single_image" # One of "single_text"; "single_image"; "both"
        
    security:
        role_admin:                     ROLE_USER
        
    dashboard:
        groups:
            
            sonata.admin.group.websites:
                label:           Websites
                label_catalogue: WebSiteBundle
                icon:            '<i class="fa fa-server"></i>'
                items:
                    - splash.website.admin.site
                    - splash.website.admin.commits
            
            
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
#                    - sonata.user.admin.group                    
                    
            sonata.admin.group.system:
                label: System
                icon:  '<i class="fa fa-tasks"></i>'
                items:
                    - sonata.admin.tasks
                    - sonata.admin.workers
                    - sonata.admin.tokens
                    
    templates:
        layout:                         SonataAdminBundle::standard_layout.html.twig
        ajax:                           SonataAdminBundle::ajax_layout.html.twig
        list:                           SonataAdminBundle:CRUD:list.html.twig
        show:                           SonataAdminBundle:CRUD:show.html.twig
        show_compare:                   SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                           SonataAdminBundle:CRUD:edit.html.twig
        history:                        SonataAdminBundle:CRUD:history.html.twig
        preview:                        SonataAdminBundle:CRUD:preview.html.twig
        delete:                         SonataAdminBundle:CRUD:delete.html.twig
        batch:                          SonataAdminBundle:CRUD:list__batch.html.twig
        acl:                            SonataAdminBundle:CRUD:acl.html.twig
        action:                         SonataAdminBundle:CRUD:action.html.twig
        select:                         SonataAdminBundle:CRUD:list__select.html.twig
        filter:                         SonataAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      SonataAdminBundle:Core:dashboard.html.twig
        search:                         SonataAdminBundle:Core:search.html.twig
        batch_confirmation:             SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:                SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     SonataAdminBundle:Block:block_admin_list.html.twig
        user_block:                     SonataUserBundle:Admin/Core:user_block.html.twig
        add_block:                      SonataAdminBundle:Core:add_block.html.twig
        pager_links:                    SonataAdminBundle:Pager:links.html.twig
        pager_results:                  SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:              SonataAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            SonataAdminBundle:Block:block_search_result.html.twig
        action_create:                  SonataAdminBundle:CRUD:dashboard__action_create.html.twig
        button_acl:                     SonataAdminBundle:Button:acl_button.html.twig
        button_create:                  SonataAdminBundle:Button:create_button.html.twig
        button_edit:                    SonataAdminBundle:Button:edit_button.html.twig
        button_history:                 SonataAdminBundle:Button:history_button.html.twig
        button_list:                    SonataAdminBundle:Button:list_button.html.twig
        button_show:                    SonataAdminBundle:Button:show_button.html.twig        