################################################################################
# WEBSITES WEBSERVICE ROUTES
################################################################################

# WebSite SOAP Acces
splash_website_soap:
    path:     /{SiteId}/soap
    defaults:
        _controller: WebSiteBundle:SOAP:main
