services:

    ################################################################################
    # SPLASH WebSites manager Service
    splash.website.manager:
        class: WebSiteBundle\Services\WebSiteManager
        public: true
        arguments:
            - '@doctrine.orm.website_entity_manager'
            - '@event_dispatcher'
            - '%database_name%'
            
    ########################################################################
    # Splash WebSite Database Event Listener
    splash.website.EventListener:
        class:      WebSiteBundle\EventListener\DatabaseEventListener
        calls:
            - [ setTaskingService,  [ '@TaskingService'] ]
        tags:
            - { name: doctrine.event_listener, event: postConnect }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelTerminate }  
            
    ################################################################################
    # SPLASH WebSite Bundle Site Sonata Admin Service
    splash.website.admin.site:
        class: WebSiteBundle\Admin\SiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Websites", label: "Sites" }
        arguments:
            - ~
            - WebSiteBundle\Entity\Site
            - WebSiteBundle:SiteCRUD
        calls:
            - [ setTemplate,        [ show, WebSiteBundle:CRUD/Site:view.html.twig]]
            - [ setWebSitemanager,  [ '@splash.website.manager'] ]
            
#            - [ setTranslationDomain, [NodesBundle]]

    ################################################################################
    # SPLASH WebSite Bundle Commits Sonata Admin Service
    splash.website.admin.commits:
        class: WebSiteBundle\Admin\CommitsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Websites", label: "Commits" }
        arguments:
            - ~
            - WebSiteBundle\Entity\Commits
            - ~