#web_site:
#    resource: "@WebSiteBundle/Resources/config/routing.yml"
#    prefix:   /


sonata:
    resource: routing/sonata.yml
    prefix: /

splash:
    resource: routing/splash.yml
    prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

