services:
    
    ################################################################################
    # SPLASH OsPos Bundle Database Service
    splash.databases.ospos:
        class: Databases\OsPosBundle\Services\DatabaseManager
        tags:
            - { name: kernel.event_listener,    event: splash.databases.list,   method: onDatabaseListAction }
#        arguments:
#            - ~
#            - WebSiteBundle\Entity\Commits
#            - ~
            
            