services:
    
    ################################################################################
    # SPLASH OsPos Bundle Database Service
    splash.databases.ospos:
        class: Databases\OsPosBundle\Services\DatabaseManager
        tags:
            - { name: kernel.event_listener,    event: splash.databases.list,       method: onDatabaseListAction }
            - { name: kernel.event_listener,    event: splash.databases.editform,    method: onEditFormAction }
        arguments:
            - "@splash.website.manager"
#            - "@doctrine.orm.entity_manager"
#            - WebSiteBundle\Entity\Commits
#            - ~
            
    ########################################################################
    # Splash OsPos Bundle Database Data Transformer
    # Convert In/Out Doctrine Objects Fields to Splash Standard Format
    splash.databases.ospos.transformer:
        class:      Databases\OsPosBundle\Services\DataTransformer
        public:     true
        arguments:  ["@translator"]
            